name: Rüyacı Bacı Kütüphane Güncelleyici

on:
  schedule:
    - cron: '0 0 * * *' # Her gece yarısı çalışır
  workflow_dispatch: # İstediğinde manuel çalıştırma butonu ekler

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Bağımlılıkları Yükle
        run: |
          pip install playwright
          playwright install chromium
      - name: Botu Çalıştır
        run: python scraper.py
      - name: Verileri Kaydet ve Pushla
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kutuphane.json
          git commit -m "Kütüphane güncellendi: $(date)" || exit 0
          git push
